name: 'Install ziglint'
description: 'Installs the ziglint tool for static analysis of Zig code'
icon: 'download-cloud'
color: 'blue'
inputs:
  binary-name:
    description: 'Name to install the ziglint binary as'
    required: true
    default: 'ziglint'
  token:
    description: 'GitHub API token to use for downloading ziglint'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install nightly Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    - name: Set path separator (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: echo "SEPARATOR=\\\\" >> "$GITHUB_ENV"
      shell: bash
    - name: Set path separator (non-Windows)
      if: ${{ runner.os != 'Windows' }}
      run: echo "SEPARATOR=/" >> "$GITHUB_ENV"
      shell: bash
    - run: node $GITHUB_ACTION_PATH${{env.SEPARATOR}}index.js ${{ inputs.binary-name }} ${{ inputs.token }}
      shell: bash
