name: 'Install ziglint'
description: 'Installs the ziglint tool for static analysis of Zig code'
icon: 'download-cloud'
color: 'blue'
inputs:
  binary-name:
    description: 'Name to install the ziglint binary as'
    required: true
    default: 'ziglint'

runs:
  using: 'node16'
  main: 'index.js'
