name: 'Install ziglint'
description: 'Installs the ziglint tool for static analysis of Zig code'
icon: 'download-cloud'
color: 'blue'
inputs:
  binary-name:
    description: 'Name to install the ziglint binary as'
    required: true
    default: 'ziglint'
  token:
    description: 'GitHub API token to use for downloading ziglint'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install nightly Zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - run: node index.js ${{ inputs.binary-name }} ${{ inputs.token }}
      shell: bash
