name: 'Example #1 (main)'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install ziglint
        uses: AnnikaCodes/install-ziglint@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint code
        run: ziglint
