name: 'Example #2'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install ziglint
        uses: AnnikaCodes/install-ziglint@v0.1
        with:
          binary-name: a_wacky_name_for_the_binary
      - name: Lint code
        run: a_wacky_name_for_the_binary
